version: '3'
services:
  website:
    image: selwyncc
    ports:
      - 80:80
      - 443:443
    restart: always
  cheers-receiver:
    image: cheers-receiver
    volumes:
      - ./cheers-db:/app/cheers-db
    environment:
      LEVELDOWN_DB: '/app/cheers-db'
    ports:
      - 3293:3293
    restart: always
