version: '3'
services:
  caddy:
    build:
      context: github.com/abiosoft/caddy-docker.git
      args:
        plugins: ratelimit
    volumes:
      - ./caddyfile:/etc/Caddyfile
      - ./dist:/srv
      - /tmp/caddy:/root/.caddy
    ports:
      - 80:80
      - 443:443
  cheers-receiver:
    image: cheers-receiver
    volumes:
      - ./cheers-db:/app/cheers-db
    environment:
      LEVELDOWN_DB: '/app/cheers-db'
    ports:
      - 3293:3293
